config {
  type: "assertion",
  name: "nsec_metrics_validation",
  description: "Validates that src_deprivation_by_constituencies matches constituency_metrics."
}

WITH src AS (
  SELECT 
    ROUND(SUM(fulltime_students),2) AS fulltime_students,
    ROUND(SUM(intermediate_occupations),2) AS intermediate_occupations,
    ROUND(SUM(managerial_administrative_and_professional_occupations),2) AS managerial_administrative_and_professional_occupations,
    ROUND(SUM(routine_and_manual_occupations),2) AS routine_and_manual_occupations,
    ROUND(SUM(never_worked_longterm_unemployed),2) AS never_worked_longterm_unemployed
  FROM ${ref("fact_national_socio_economic_class")}
  WHERE constituency_name IS NOT NULL
),

upstream AS (
  SELECT 
    ROUND(SUM(fulltime_students),2) AS fulltime_students,
    ROUND(SUM(intermediate_occupations),2) AS intermediate_occupations,
    ROUND(SUM(managerial_administrative_and_professional_occupations),2) AS managerial_administrative_and_professional_occupations,
    ROUND(SUM(routine_and_manual_occupations),2) AS routine_and_manual_occupations,
    ROUND(SUM(never_worked_longterm_unemployed),2) AS never_worked_longterm_unemployed
FROM ${ref("constituency_metrics")}
)

-- Compare aggregated results from both sources
SELECT *
FROM src

EXCEPT DISTINCT

SELECT *
FROM upstream
