config {
  type: "assertion",
  name: "nsec_metrics_validation",
  description: "Validates that src_deprivation_by_constituencies matches constituency_metrics."
}

WITH src AS (
  SELECT 
    SUM(fulltime_students) AS fulltime_students,
    SUM(intermediate_occupations) AS intermediate_occupations,
    SUM(managerial_administrative_and_professional_occupations) AS managerial_administrative_and_professional_occupations,
    SUM(routine_and_manual_occupations) AS routine_and_manual_occupations,
    SUM(never_worked_longterm_unemployed) AS never_worked_longterm_unemployed
     FROM ${ref("fact_national_socio_economic_class")}
),

upstream AS (
  SELECT 
    SUM(fulltime_students) AS fulltime_students,
    SUM(intermediate_occupations) AS intermediate_occupations,
    SUM(managerial_administrative_and_professional_occupations) AS managerial_administrative_and_professional_occupations,
    SUM(routine_and_manual_occupations) AS routine_and_manual_occupations,
    SUM(never_worked_longterm_unemployed) AS never_worked_longterm_unemployed
FROM ${ref("constituency_metrics")}
)

-- Compare aggregated results from both sources
SELECT *
FROM src

EXCEPT DISTINCT

SELECT *
FROM upstream
