config {
    type: "assertion"
}

  -- File: nsec_variable_acceptable_values.sqlx
SELECT
DISTINCT
  variable
FROM
  ${ref("src_national_socio_economic_class")}
WHERE
  variable NOT IN ( 'higher_managerial_administrative_and_professional_occupations',
    'lower_managerial_administrative_and_professional_occupations',
    'intermediate_occupations',
    'small_employers_and_own_account_workers',
    'lower_supervisory_and_technical_occupations',
    'semiroutine_occupations',
    'routine_occupations',
    'never_worked_longterm_unemployed',
    'fulltime_students')
