config {
  type: "assertion",
  name: "total_premises_metric_validation",
  description: "Validates that total premises and constituency counts match between dim_premises and constituency_metrics."
}

WITH total_premises AS (
  SELECT
    COUNT(premisesid) AS total_premises
  FROM ${ref("dim_premises")}
  WHERE constituency_name IS NOT NULL
),

total_premises_metric AS (
  SELECT
    SUM(total_premises) AS total_premises
  FROM ${ref("constituency_metrics")}
)

-- Direct comparison of aggregated values
SELECT * 
FROM total_premises

EXCEPT DISTINCT

SELECT * 
FROM total_premises_metric