path:
  original_file: 'premises-licence-register.csv'
  replaced_nulls: 'nan_replacement.csv'
  distinct_ids: 'enforced_uniqueness.csv'
  post_google_api: 'operation_vs_permclose.csv'
  manually_checked: 'check_webscrape.csv'
webscrape:
  local_council_url: 'https://www.gov.uk/find-local-council'
  local_council_postcode_search: 'postcode'
  local_council_button_selector: '#local-locator-form > button'
  local_council_two_options: '#content > div > div.govuk-grid-column-two-thirds.article-container > h2'
  local_council_first_option: '#content > div > div.govuk-grid-column-two-thirds.article-container > div > div.county-result.group.govuk-\!-margin-bottom-8 > h3'
  local_council_second_option: '#content > div > div.govuk-grid-column-two-thirds.article-container > div > div.district-result.group > h3'
  local_council_grab: '#content > div > div.govuk-grid-column-two-thirds.article-container > div > div > p:nth-child(1) > strong'
  royal_url: 'https://www.royalmail.com/find-a-postcode'
  royal_search_id: 'edit-rml-postcode-finder-postal-code'
  royal_selector_postcode: '#paragraph-9021 > div.container > div > div > div > div.address-detail.col-md-7 > div.postalcode'
  royal_cookie_accept_button_id: "consent_prompt_submit"
  twfy_url: 'https://www.theyworkforyou.com/'
  twfy_search_id: 'postcode'
  twfy_click_button: 'body > div.hero > div > div.hero__mp-search > div > div > form > div.medium-3.columns > input'
  twfy_grab: 'body > div.person-header > div > div > div.person-header__about > p > span.person-header__about__position__constituency'
  ukp_url: 'https://members.parliament.uk/findyourmp/'
  ukp_search_id: 'SearchText'
  ukp_click_button: '#main-content > div > article > div > div > div.filter > form > div > div > button'
  ukp_grab: '#main-content > div.hero-banner.hero-banner-brand > div > div > div.col-md-8.col-no-spacing > p > a'
  authorise: y
input_datasets:
  postcodes:  'postcodes.csv'
  social_eco_class: 'NS-SEC_2021.csv'
  indices_deprivation: 'constituencies_deprivation-dashboard.csv'
output_datasets:
  google_check_file : 'checker_operation_vs_permclose.csv'
  royal_mail_check_file:  'royalmail_results.csv'
  joined_dataset: 'joined_dataset.csv'
  null_constituency:  'null_constituency.csv'
  missing_constituencies: 'mising_constituencies.csv'
  check_webscrape: 'check_webscrape.csv'
  joined_webscrape: 'check_joined_webscrape.csv'
  final_dataset: 'Final_UK_gambling_premises_social_class_and_deprivation_dataset.csv'
  enforced_uniqueness: 'enforced_uniqueness.csv'
  local_authority_filled: 'Local Authority Filled.csv'
  nan_replacement: 'nan_replacement.csv'
  google_api_results: 'gbsnsstus_complete.csv'
  untested_post_google_api: 'operation_permclose.csv'
  correlation_matrix: 'op_spearman_matrix.csv'
