path:
  original_file: 'C:\\Users\\natha\\OneDrive\\Desktop\\Kaggle\\premises-licence-register.csv'
  replaced_nulls: 'C:\\Users\\natha\\OneDrive\\Desktop\\Kaggle\\NONULLS_premises-licence-register.csv'
  distinct_ids: 'C:\\Users\\natha\\OneDrive\\Desktop\\Kaggle\\Added_FlatID_NONULLS_premises-licence-register.csv'
  post_google_api: 'C:\\Users\\natha\\OneDrive\\Desktop\\Kaggle\\operation_vs_permclose_premises-licence-register.csv'
  manually_checked: 'C:\\Users\\natha\\OneDrive\\Desktop\\done_20_01_2024_check_webscrape.csv'
webscrape:
  local_council_url: 'https://www.gov.uk/find-local-council'
  local_council_postcode_search: 'postcode'
  local_council_button_selector: '#local-locator-form > button'
  local_council_two_options: '#content > div > div.govuk-grid-column-two-thirds.article-container > h2'
  local_council_first_option: '#content > div > div.govuk-grid-column-two-thirds.article-container > div > div.county-result.group.govuk-\!-margin-bottom-8 > h3'
  local_council_second_option: '#content > div > div.govuk-grid-column-two-thirds.article-container > div > div.district-result.group > h3'
  local_council_grab: '#content > div > div.govuk-grid-column-two-thirds.article-container > div > div > p:nth-child(1) > strong'
  royal_url: 'https://www.royalmail.com/find-a-postcode'
  royal_search_id: 'edit-rml-postcode-finder-postal-code'
  royal_selector_postcode: '#paragraph-9021 > div.container > div > div > div > div.address-detail.col-md-7 > div.postalcode'
  royal_cookie_accept_button_id: "consent_prompt_submit"
  twfy_url: 'https://www.theyworkforyou.com/'
  twfy_search_id: 'postcode'
  twfy_click_button: 'body > div.hero > div > div.hero__mp-search > div > div > form > div.medium-3.columns > input'
  twfy_grab: 'body > div.person-header > div > div > div.person-header__about > p > span.person-header__about__position__constituency'
  ukp_url: 'https://members.parliament.uk/findyourmp/'
  ukp_search_id: 'SearchText'
  ukp_click_button: '#main-content > div > article > div > div > div.filter > form > div > div > button'
  ukp_grab: '#main-content > div.hero-banner.hero-banner-brand > div > div > div.col-md-8.col-no-spacing > p > a'
  authorise: y
input_datasets:
  postcodes:  'C:\\Users\\natha\\OneDrive\\Desktop\\Kaggle\\source data\\postcodes\\postcodes.csv'
  social_eco_class: 'C:\\Users\\natha\\PycharmProjects\\gambling_premises_in_the_uk\\Preparation & Cleaning Redundancies\\Key Stage Downloads - CSVs\\source_data\\NS-SEC_2021.csv'
  indices_deprivation: 'C:\\Users\\natha\\OneDrive\\Desktop\\Kaggle\\source data\\Data constituencies_deprivation-dashboard.csv'
output_datasets:
  google_check_file : 'C:\\Users\\natha\\OneDrive\\Desktop\\Kaggle\\19_01_2024_checker_operation_vs_permclose_premises-licence-register.csv'
  royal_mail_check_file:  'C:\\Users\\natha\\OneDrive\\Desktop\\Kaggle\\20_01_2024_royalmail_results.csv'
  joined_dataset: 'C:\\Users\\natha\\PycharmProjects\\gambling_premises_in_the_uk\\Preparation & Cleaning Redundancies\\Key Stage Downloads - CSVs\\joined_datasetThe_UK_gambling_premises_social_class_and_deprivation_dataset.csv'
  null_constituency:  'C:\\Users\\natha\\OneDrive\\Desktop\\Kaggle\\20_01_2024_null_constituency.csv'
  missing_constituencies: 'C:\\Users\\natha\\OneDrive\\Desktop\\20_01_2024_mising_constituencies_two.csv'
  check_webscrape: 'C:\\Users\\natha\\OneDrive\\Desktop\\20_01_2024_check_webscrape.csv'
  joined_webscrape: 'C:\\Users\\natha\\OneDrive\\Desktop\\20_01_2024_check_joined_webscrape.csv'
  final_dataset: 'C:\\Users\\natha\\PycharmProjects\\gambling_premises_in_the_uk\\Preparation & Cleaning Redundancies\\Key Stage Downloads - CSVs\\Final20_01_2024_T2202The_UK_gambling_premises_social_class_and_deprivation_dataset.csv'
  enforced_uniqueness: 'C:\\Users\\natha\\OneDrive\\Desktop\\Kaggle\\enforced_uniqueness_premises-licence-register.csv'
  local_authority_filled: 'C:\\Users\\natha\\OneDrive\\Desktop\\02_02_2024_Local Authority Filled.csv'
  nan_replacement: 'C:\\Users\\natha\\OneDrive\\Desktop\\Kaggle\\02_02_2024_nan_replacement.csv'
  google_api_results: 'C:\\Users\\natha\\OneDrive\\Desktop\\Kaggle\\gbsnsstus_complete_premises-licence-register.csv'
  untested_post_google_api: 'C:\\Users\\natha\\OneDrive\\Desktop\\Kaggle\\03_02_2024_operation_vs_permclose_premises-licence-register.csv'
  correlation_matrix: 'C:\\Users\\natha\\PycharmProjects\\gambling_premises_in_the_uk\\Preparation & Cleaning Redundancies\\Key Stage Downloads - CSVs\\08_02_2024_op_spearman_matrix.csv'
